GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/640bc3d7a74aa271a28ed903

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "",
    "subscribedToChannel": ""
}

###

DELETE http://localhost:3000/subscribers/640bc3d7a74aa271a28ed903

###

PATCH http://localhost:3000/subscribers/640bc0db0f52992fadc8593a
Content-Type: application/json

{
    "name": "",
    "subscribedToChannel": ""
}